# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/sm8250-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter bitra bladerunner bladerunner_48m,$(TARGET_DEVICE)),)

endif
