# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/bladerunner_48m/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),bladerunner_48m)

endif
